# Extending image
FROM node:carbon

# Create app directory
RUN mkdir /app
WORKDIR /app

# Install app dependencies
COPY package.json .
COPY package-lock.json .

RUN npm install

# Bundle app source
COPY . .

# Environment variables
ENV NODE_ENV test
ENV NPM_CONFIG_LOGLEVEL warn
ENV CI=true
