# Extending image
FROM node:8.11

# Create app directory
RUN mkdir /app
WORKDIR /app

# Install app dependencies
COPY package.json .
COPY package-lock.json .
COPY Makefile /app/Makefile

RUN make install_dependencies

# Bundle app source
COPY . .

# Environment variables
ENV NODE_ENV test
ENV NPM_CONFIG_LOGLEVEL warn
ENV CI=true
